version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: cinema_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinema
      MYSQL_PASSWORD: cinema
    ports:
      - "3306:3306"

